
package schoolapp;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Document;

/**
 *
 * @author Y. H. Bhosale
 */
public class Student_Window extends javax.swing.JFrame {
    
    public Student_Window() {
        initComponents();        
        fillTable();
    }    
    String photopath=null;
    public ImageIcon resizeImageI(String photopath,byte[] photo){
        ImageIcon myPhoto=null;
        if (photopath!=null) {
            myPhoto=new ImageIcon(photopath);
        }else{
            myPhoto=new ImageIcon(photo);
        }
            Image img=myPhoto.getImage();
            Image img1=img.getScaledInstance(lable_photo.getWidth(), lable_photo.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon ph=new ImageIcon(img1); 
            return ph;
    }
    
    public Connection mySqlConn(){
        Connection con=null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb1","root","root@123");
            //JOptionPane.showMessageDialog(null, "Mysql DB Connection Successful");
            return con;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Mysql DB Connection Failed");
            return null;
        }
    }
    
    public ArrayList<Student_Bean> retrieveData(){
        ArrayList<Student_Bean> al=null;
                al=new ArrayList<Student_Bean>();
       
        try {
            Connection conn=mySqlConn();
            String qry="select * from student";
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(qry);
            Student_Bean student;
            while (rs.next()) {
                student =new Student_Bean(rs.getInt(1),rs.getString("name"),Float.parseFloat(rs.getString(3)),rs.getString(4),rs.getBytes("photo"));                
                al.add(student);
              }
           
        } catch (Exception e) {
            System.out.println(e);
        }
       return al; 
    }
    
    public void fillTable(){
        ArrayList<Student_Bean> al=retrieveData();
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0); // Empty/clear the table
        Object[] row=new Object[4];
        for (int i = 0; i < al.size(); i++) {
            row[0]=al.get(i).getId();
            row[1]=al.get(i).getName();
            row[2]=al.get(i).getFees();
            row[3]=al.get(i).getDob();
            model.addRow(row);
        }
        //model.setRowCount(0);
    }
    
    public void showItemToFields(int index){
        jTextField1_id.setText(Integer.toString(retrieveData().get(index).getId()));
        jTextField2_name.setText(retrieveData().get(index).getName());
        jTextField3_fees.setText(Float.toString(retrieveData().get(index).getFees()));
        
        try{
            java.util.Date dob=null;
            dob=new SimpleDateFormat("dd-MM-yyyy").parse((String)retrieveData().get(index).getDob());
            jDateChooser1_dob.setDate(dob);
        }catch(ParseException e){
            //Logger.getLogger(Student_Window.class.getName()).log(Level.SEVERE,null,e);
            System.out.println("Error in showItemToFields method...");
        }
        lable_photo.setIcon(resizeImageI(null, retrieveData().get(index).getPhoto()));
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1_id = new javax.swing.JTextField();
        jTextField2_name = new javax.swing.JTextField();
        jTextField3_fees = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDateChooser1_dob = new com.toedter.calendar.JDateChooser();
        lable_photo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3_insert = new javax.swing.JButton();
        jButton4_update = new javax.swing.JButton();
        jButton5_delete = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField1_search = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(253, 223, 132));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("CSMSS Chh. Shahu College of Engineering");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setText("Aurangabad, Maharashtra, India");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolapp/cscoecollegelogo.jpg"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Student Information");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Student Id:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Student name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Fees:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Date of Birth:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Photo:");

        jTextField1_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1_id.setForeground(new java.awt.Color(0, 0, 153));

        jTextField2_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField2_name.setForeground(new java.awt.Color(0, 0, 153));

        jTextField3_fees.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField3_fees.setForeground(new java.awt.Color(0, 0, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Roll Number", "Name", "Fees", "Date Of Birth"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jDateChooser1_dob.setDateFormatString("dd-MM-yyyy");

        lable_photo.setForeground(new java.awt.Color(255, 255, 255));
        lable_photo.setOpaque(true);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder_red.png"))); // NOI18N
        jButton1.setText("Select Photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_violet_delete.png"))); // NOI18N
        jButton2.setText("New/Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3_insert.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3_insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cross.png"))); // NOI18N
        jButton3_insert.setText("Insert/Save");
        jButton3_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_insertActionPerformed(evt);
            }
        });

        jButton4_update.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_add.png"))); // NOI18N
        jButton4_update.setText("Update/Edit");
        jButton4_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_updateActionPerformed(evt);
            }
        });

        jButton5_delete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/erase.png"))); // NOI18N
        jButton5_delete.setText("Delete/Remove");
        jButton5_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_deleteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Search The Student (By Name):");

        jTextField1_search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1_search.setForeground(new java.awt.Color(255, 0, 0));
        jTextField1_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1_searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(194, 194, 194)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel5)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField1_id, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lable_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextField2_name, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jTextField3_fees, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jDateChooser1_dob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(84, 84, 84)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3_insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1073, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addComponent(jTextField1_search, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addGap(140, 140, 140))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(jButton3_insert)
                                .addGap(25, 25, 25)
                                .addComponent(jButton4_update))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1_id))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                    .addComponent(jTextField3_fees, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jDateChooser1_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lable_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jButton5_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTextField1_search, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser=new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter fnef=new FileNameExtensionFilter("*.images", "jpg","png");
        chooser.addChoosableFileFilter(fnef);
        int ans=chooser.showSaveDialog(null);
        if (ans==JFileChooser.APPROVE_OPTION) {
           File selectedPhoto=chooser.getSelectedFile();
           String path=selectedPhoto.getAbsolutePath();
           lable_photo.setIcon(resizeImageI(path, null));
          this.photopath=path;
        }else{
            System.out.println("Photo Not Selected ....");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_insertActionPerformed
       //JOptionPane.showMessageDialog(null, "Button Clicked");
        if((jTextField1_id.getText()!=null || jTextField2_name!=null
                || jTextField3_fees!=null || jDateChooser1_dob!=null)
                &&photopath!=null){
               //jTextField3_fees.getText().toString()
               try {
                Connection con=mySqlConn();
                PreparedStatement ps=con.prepareStatement("insert into student"
                        + "(id,name,fees,dob,photo) values (?,?,?,?,?)");
                ps.setInt(1,Integer.parseInt(jTextField1_id.getText().toString()));
                //System.out.println("id is "+jTextField1_id.getText().toString());
                ps.setString(2,jTextField2_name.getText().toString());
                //System.out.println("name is "+jTextField2_name.getText().toString());
                ps.setFloat(3, Float.parseFloat(jTextField3_fees.getText().toString()));
                //System.out.println("Fees is "+jTextField3_fees.getText().toString());
                   SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
                   String dob1=sdf.format(jDateChooser1_dob.getDate());
                   ps.setString(4,dob1);
                   //System.out.println("DOB is "+jDateChooser1_dob.getDate());
                   InputStream is=new FileInputStream(new File(photopath));
                   ps.setBlob(5, is);
                   int i=ps.executeUpdate();
                   fillTable();
                   //System.out.println("i is "+i);
                   if(i>=1){
                   JOptionPane.showMessageDialog(null, i+"Student Inserted Succussfully...");
                   jTextField1_id.setText("");
                   jTextField2_name.setText("");
                   jTextField3_fees.setText("");
                   lable_photo.setText("");
                   }
                   else
                   JOptionPane.showMessageDialog(null, i+"Student insertion failed to database...");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Student insertion failed "+e);
            }
        }else{
                JOptionPane.showMessageDialog(null, "All Fields are compulsory ");
        }
        //Sysstem.out.println("id is "+jTextField1_id.getText().toString());
        //System.out.println("name is "+jTextField2_name.getText().toString());
        //System.out.println("Fees is "+jTextField3_fees.getText().toString());
        //System.out.println("DOB is "+jDateChooser1_dob.getDate());
        //System.out.println("PHoto  "+photopath);
    }//GEN-LAST:event_jButton3_insertActionPerformed

    private void jButton4_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_updateActionPerformed
        if (jTextField1_id.getText()!=null || jTextField2_name!=null
                || jTextField3_fees!=null || jDateChooser1_dob!=null){
            String qry=null;
            PreparedStatement ps=null;
            Connection con=mySqlConn();
            
            //if photopath is null
            if (photopath==null) {
                try {
                    qry="update student set name=?, fees=?,dob=? where id=?";
                    ps=con.prepareStatement(qry);
                    ps.setString(1,jTextField2_name.getText().toString());
                    ps.setFloat(2,Float.parseFloat(jTextField3_fees.getText().toString()));
                    SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
                    String sdate=sdf.format(jDateChooser1_dob.getDate());
                    ps.setString(3,sdate);
                    ps.setInt(4,Integer.parseInt(jTextField1_id.getText().toString()));
                    
                    int res=ps.executeUpdate();                   
                    if(res>=1)
                        JOptionPane.showMessageDialog(null, res+" Record successfully Updated..");
                    else
                        JOptionPane.showMessageDialog(null, res+" Record Updation Failed...");
                } catch (Exception e) {                    
                    JOptionPane.showMessageDialog(null, e);
                }
            }else{ //if with photo update
                try{
                InputStream is=new FileInputStream(new File(photopath));
                
                qry="update student set name=?,fees=?,dob=?,photo=? where id=?";
                ps=con.prepareStatement(qry);
                ps.setString(1,jTextField2_name.getText().toString());
                ps.setFloat(2,Float.parseFloat(jTextField3_fees.getText().toString()));
                SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
                String sdate=sdf.format(jDateChooser1_dob.getDate());
                ps.setString(3,sdate);
                ps.setBlob(4, is);
                ps.setInt(5,Integer.parseInt(jTextField1_id.getText().toString()));
                
                int i=ps.executeUpdate();                   
                if(i>=1)
                        JOptionPane.showMessageDialog(null, i+" Record successfully Updated..");
                    else
                        JOptionPane.showMessageDialog(null, i+" Record Updation Failed...");
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            fillTable();
        }else{
              JOptionPane.showMessageDialog(null, "All fields are compulsory/Invalid Inputs...");
        }                
    }//GEN-LAST:event_jButton4_updateActionPerformed

    private void jButton5_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_deleteActionPerformed
        
        if (jTextField1_id.getText().equals("")){
            try{
            String qry="delete from student where id=?";
            Connection con=mySqlConn();
            PreparedStatement ps=con.prepareStatement(qry);
            ps.setInt(1,Integer.parseInt(jTextField1_id.getText().toString()));
            int x=ps.executeUpdate();
            if(x>=1)
                JOptionPane.showMessageDialog(null, x+" Record Deleted from Database...");     
            else
                JOptionPane.showMessageDialog(null, x+" Record Deleted Failed...");     
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);     
            }            
            fillTable();
        }else{
        JOptionPane.showMessageDialog(null, "Please Enter Student Id, to delete");     
        }        
    }//GEN-LAST:event_jButton5_deleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
           int ind=jTable1.getSelectedRow();
            showItemToFields(ind);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_searchKeyReleased
        //JOptionPane.showMessageDialog(null, jTextField1_search.getText().toString());     
        ArrayList<Student_Bean> al=null;
                al=new ArrayList<Student_Bean>();
       String val=jTextField1_search.getText().toString();
        try {
            Connection conn=mySqlConn();
            //String qry="select * from student where (name like '%"+val+"%' or id like %"+Integer.parseInt(val)+"%)";
            String qry="select * from student where name like '%"+val+"%'";
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(qry);
            Student_Bean student;
            while (rs.next()) {
                student =new Student_Bean(rs.getInt(1),rs.getString("name"),Float.parseFloat(rs.getString(3)),rs.getString(4),rs.getBytes("photo"));                
                al.add(student);
              }
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0); // Empty/clear the table
        Object[] row=new Object[4];
        for (int i = 0; i < al.size(); i++) {
            row[0]=al.get(i).getId();
            row[1]=al.get(i).getName();
            row[2]=al.get(i).getFees();
            row[3]=al.get(i).getDob();
            model.addRow(row);
        }
           
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jTextField1_searchKeyReleased
    //Clear the fields
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1_id.setText("");
        jTextField1_search.setText("");
        jTextField2_name.setText("");
        jTextField3_fees.setText("");
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Window().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3_insert;
    private javax.swing.JButton jButton4_update;
    private javax.swing.JButton jButton5_delete;
    private com.toedter.calendar.JDateChooser jDateChooser1_dob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1_id;
    private javax.swing.JTextField jTextField1_search;
    private javax.swing.JTextField jTextField2_name;
    private javax.swing.JTextField jTextField3_fees;
    private javax.swing.JLabel lable_photo;
    // End of variables declaration//GEN-END:variables
}
